### ISSUE TITLE
CancellationTokenSource.Token

### ISSUE THREAD

**Issue by shersh** [ParsePlatform/Parse-SDK-dotNET#1]
public CancellationToken Token {
      get {
        return new CancellationToken(this);
      }
    }

It's bad to create new token every time in getter.

**Comment by hallucinogen** [comment]
Thanks for the report. Although this seems very inefficient, the CancellationToken will still work properly. And this is compliant with Microsoft's `CancellationTokenSource`: http://referencesource.microsoft.com/#mscorlib/system/threading/CancellationTokenSource.cs,159
