### ISSUE TITLE
iOS SDK v1.6.0 breaking bug: ParseUser.SignUpAsync() never throws any exceptions, even on bad data or duplicate users

### ISSUE THREAD

**Issue by bbartlett** [ParsePlatform/Parse-SDK-dotNET#10]
In the v1.6.0 Parse SDK for iOS (from nuget), ParseUser.SignUpAsync() no longer throws any exceptions, even on bad data or duplicate users.  Using TodoParseAuth as a test, in v1.5.5, exceptions are thrown for things like invalid email addresses ( eg: ".@here.com") or users already existing, but as of the 1.6.0 update, exceptions are no longer thrown.  Code simply passes through to the next line, with ParseUser.CurrentUser NOT being set to null, but instead being set to an invalid object (where ParseUser.CurrentUser.ObjectId is null).

**Comment by hallucinogen** [comment]
Hi @bbartlett,

Thank you for your report. This seems like a valid bug. We'll investigate this issue further and will let you know if there's any progress/fix.

**Comment by richardjrossiii** [comment]
Valid bug. Thanks for finding this! Sending a PR shortly.
