### ISSUE TITLE
ParsePushService Android crashes on receive push notification w/ null payload string

### ISSUE THREAD

**Issue by richardjrossiii** [ParsePlatform/Parse-SDK-dotNET#104]
When a Unity app on Android receives a push notification, an exception is thrown if the payload is null. This can be an issue if the push was sent from another push provider besides Parse.

The error seems to be originating from this code:
https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParsePush/src/main/java/com/parse/ParsePushService.java#L138-L140

(This bug originated from an external bug report).

**Comment by giomatiashvili** [comment]
Here I fixed that problem and recompiled jar, if payload is null it just escapes function without any crash.

Download: [ParsePush.jar](https://drive.google.com/open?id=0B3rbhKVZ4R8dVmlUZHhKbzZXNzQ)
