### ISSUE TITLE
Exception is thrown from ParseClient.Initialize

### ISSUE THREAD

**Issue by PauliusLiekis** [ParsePlatform/Parse-SDK-dotNET#111]
I tried compiling latest code for Unity4. Exception is thrown from ParseClient.Initialize:

"Cannot register a type that does not implement the default constructor!"

It happens in ObjectSubclassingController.cs:94, because it executes this line:

RegisterSubclass(typeof(ParseObject));

Problem is that ParseObject doesn't have public default constructor, thus RegisterSubclass method throws an exception.

Is there a way to make this code work?

**Comment by PauliusLiekis** [comment]
@richardjrossiii this still doesn't - I still get the same error. Have you tried it yourself?

My understanding is that ReflectionHelpers.FindConstructor tries to call extension method GetConstructors, but it doesn't call extension method ReflectionHelpers.GetConstructors, but calls instance method Type.GetConstructors instead, because:

* An extension method will never be called if it has the same signature as a method defined in the type. (from MSDN)

And Type.GetConstructors defaults to Type.GetConstructors(BindingFlags.Public | BindingFlags.Instance).

Am I missing something?

**Comment by richardjrossiii** [comment]
@PauliusLiekis The issue has been fixed, although if you don't build it yourself you won't see the fix yet. We'll need to release a new version of the SDK to do that, which will be forthcoming soonish.

**Comment by PauliusLiekis** [comment]
@richardjrossiii I'm building myself, so yeah I have everything latest. Maybe the problem is that I'm using MonoDevelop to compile it, but as I said it looks like GetConstructors extension function indeed shouldn't get called according to MSDN specification of extension functions.
