### ISSUE TITLE
ParseUser.Logout(); Crashes unity? How can i log out?

### ISSUE THREAD

**Issue by ViolentCrumble** [ParsePlatform/Parse-SDK-dotNET#114]
````
public void LogOut()
{
    if (ParseUser.CurrentUser != null)
    {
        ParseUser.LogOut();
    }
    if (FB.IsLoggedIn)
    {
        FB.LogOut();
    }
}
```


This crashes unity... when it shouldn't

**Comment by ViolentCrumble** [comment]
public void LogOut()
    {
        if (ParseUser.CurrentUser != null)
        {
            ParseUser.LogOut();
        }
        if (FB.IsLoggedIn)
        {
            FB.LogOut();
        }
    }


This crashes unity... when it shouldn't

**Comment by richardjrossiii** [comment]
Thanks for the report. Which version of the SDK are you using? Can we get an exception stack trace?

**Comment by ViolentCrumble** [comment]
I have read all the docs.. and of course im using the latest sdk.. its just one line of code i dont see how i can get that wrong.. And before i log out i check (How u tell me to check) if im signed in? so how does it crash?


Im back at my pc now.. how do i get a stack trace? it completely locks up unity and i lost hours of work.. only way to reuse unity was to close the process manually.

**Comment by ViolentCrumble** [comment]
WEll i found the editor that log that appears after unity crashes.. i hope thats what u need?

i think the new stuff is at the bottom.

**Comment by ViolentCrumble** [comment]
Still no response?? I cant even make a logout function cause it just crashes.

**Comment by richardjrossiii** [comment]
I've looked at the log and I cannot see anything that looks like the editor crash is directly related to parse. My best guess is that there's some kind of flaw in Unity's debugger, and that the issue lies with them (even if there is a bug in our code-base, it shouldn't ever crash Unity Editor).

**Comment by ViolentCrumble** [comment]
hmm strange ok. I amt rying to extend out the logout function and it has stopped the crashing.. still now redirecting but at least its not crashing..

```
public void LogOut()
    {

        //try and register user and catch any errors.
        try
        {

            Task logoutTask = ParseUser.LogOutAsync().ContinueWith(t => {
                if (t.IsFaulted)
                {
                    // Errors from Parse Cloud and network interactions
                    using (IEnumerator<System.Exception> enumerator = t.Exception.InnerExceptions.GetEnumerator())
                    {
                        if (enumerator.MoveNext())
                        {
                            ParseException error = (ParseException)enumerator.Current;
                            Debug.Log(error.Message);
                            
                            // error.Message will contain an error message
                            // error.Code will return "OtherCause"
                        }
                    }
                }

                NotLoggedInMenu.SetActive(true);
                LoggedInMenu.SetActive(false);

            });
        }
        catch (InvalidOperationException e)
        {
            Debug.Log(e.Message);
            

            // Error from the SDK logic checks
            // e.Message will contain the specific error
            // ex: "Cannot sign up user with an empty name."
        }
        
    }
```

Parse really needs some better working docs though almost everything has been nothing like the examples.

**Comment by dhanrajsinh24** [comment]
I am having problems in Unity 5.3.0. When i call "ParseUser.LogOut()", Unity Hangs and i have to force close Unity and start it again.

**Comment by ViolentCrumble** [comment]
see what i did above? use my code to try and catch the error.

Noone at Parse will help you.
