### ISSUE TITLE
The type 'System.Object' is defined in an assembly that is not reference

### ISSUE THREAD

**Issue by gemsuraj** [ParsePlatform/Parse-SDK-dotNET#117]
This error is occurring when sending the object as a model from controller to view. Model binding is working due to this.

```
Compiler Error Message: CS0012: The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Line 1000:EndContext("~/Areas/Admin/Views/Users/Details.cshtml", 5025, 43, true);
Line 1001:
Line 1002:WriteAttribute("src", Tuple.Create(" src=\"", 5068), Tuple.Create("\"", 5129)
Line 1003:            
Line 1004:            #line 67 "D:\DS_Projects_Archived\Apptitude\Code\Apptitude\Areas\Admin\Views\Users\Details.cshtml"
````

**Comment by richardjrossiii** [comment]
Which platform are you seeing this on? Mono? UWP? Unity? WinRT?

Which version of the SDK are you using?

There's nothing in that error message that indicates to me that Parse is what's causing this error.

**Comment by gemsuraj** [comment]
Platform is winRT

I'm using the latest version installed via nuget

My .net version is 4.5

The error comes when you use the parse object in views. The error says that
there's no reference to "system.object" in the target assembly (parse.dll).
i'll send you the complete stack trace soon. or you can simply check it my
using Parseuser.Current.Email in any view. it will generate this error.




*Suraj Sharma*   .Net Web Developer[image: photo]Mobile: +91 9768 58 4338
<+91+9768+58+4338>
Skype: gemsuraj <https://webapp.wisestamp.com/#>
Website: http://www.codeblock.in <http://www.codeblock.in/>
Address: Malad East, Mumbai, Maharashtra, 400 097
<http://facebook.com/suraj.knowbie>
<http://us.linkedin.com/in/surajknowbie>  <http://twitter.com/surajknowbie>
<http://plus.google.com/+SurajSharmaIN>  <http://behance.net/surajsharma>
<http://pinterest.com/surajknowbie>

**Comment by richardjrossiii** [comment]
Unable to reproduce. I just added the following binding to an empty Windows 8.1 store application:

```
<TextBlock HorizontalAlignment="Left" Margin="164,229,0,0" TextWrapping="Wrap" Text="{Binding CurrentUser.Email, FallbackValue=Current User Email}" VerticalAlignment="Top">
    <TextBlock.DataContext>
        <Parse:ParseUser/>
    </TextBlock.DataContext>
</TextBlock>
```

And it works swimmingly using NuGet.

**Comment by gemsuraj** [comment]
Sorry, I meant asp.net mvc. The error is occurring while developing a
asp.net web application (framework 4.5).

**Comment by richardjrossiii** [comment]
Ahh, that would be why. Our SDK currently doesn't support ASP.NET as a platform, but we have recently talked amongst the team (yesterday even) about supporting this as a platform. I've opened #121 to publicly track ASP.NET as a platform, so know that we are aware and planning to eventually get there.

Unfortunately I can't give an ETA at this time.

**Comment by gemsuraj** [comment]
Thanks Richard.
