### ISSUE TITLE
Object doesn't get updated after calling SaveAsync on Parse Unity 1.6.2

### ISSUE THREAD

**Issue by birdkingz** [ParsePlatform/Parse-SDK-dotNET#120]
I have a column ("DataDict") storing type of Dictionary (let say the variable name is call "dataDict")

Recently I've updated to Parse Unity 1.6.2 and I found out that whenever I make an update to dataDict, it doesn't get updated to the server.

For example:

    Dictionary<string, object> dict = ParseUser.CurrentUser["DataDict"] as Dictionary<string, object>;
    dict["name"] = "something new";
    // after I call ParseUser.CurrentUser.SaveAsync()
    // the server should have updated the dictionary 
    // but it's no longer working as what I expected after I've updated to Parse 1.6.2
Does anyone know what's going on?

I noticed one of the keypoint that listed in the changelogs:
Removed 'mutable containers' functionality, significantly enhances performance.

Does this affected my codes? How should I fix it?

**Comment by birdkingz** [comment]
I

**Comment by birdkingz** [comment]
Ok, I've solved this by calling
ParseUser.CurrentUser["DataDict"] = dict;

**Comment by richardjrossiii** [comment]
@birdkingz  that is correct. Now we make a copy of dictionaries and arrays passed into parse, which requires you to set the dictionary again afterward.
