### ISSUE TITLE
Custom Events not showing up in explorer

### ISSUE THREAD

**Issue by MarcusSpecht** [ParsePlatform/Parse-SDK-dotNET#125]
I am not sure if this is really related to the .Net SDK since problem occurs with Analytics explorer. But for now I only use parse with Parse-SDK-doNET. So here we go:

This works:
Analytics -> Events -> Custom Breakdown Count of event = showing updated event after several roughly 5 minutes

This doesn't work:
Analytics -> Explorer -> Raw Data -> Run Query for custom events unfiltered = doesn't show events

1. It shows an older TestEvent without dimensions. The event not showing up has some dimensions
2. Already googled a lot and found out the following
   * Event Name has to be alphanumeric only, not whitespace. Done.
   * Max of 8 dimension are stored. I have less but values or not only aphanumeric.
   * Explorer Data can show up late even 1 or 2 days (I guess by design to not overuse for life or real time analytics)
3. I am storing the foollowing dimesions
   * username of current user
   * string with whitespace
   * comma separated array of strings as string (but bot very long < 100 chars)
   * an integer as string

Any ideas?

**Comment by hallucinogen** [comment]
Hi there,

Since you mentioned that it works on Analytics -> Events -> Custom Breakdown Count, I assume this is a backend issue that fails to display the event on Analytics -> Explorer -> Raw Data -> Run Query. You can file a backend issue here: https://developers.facebook.com/bugs
