### ISSUE TITLE
Unity+WindowsPhone dll conflict with Parse dll

### ISSUE THREAD

**Issue by sercante** [ParsePlatform/Parse-SDK-dotNET#130]
Hi, this was a closed issue #126  but since I didn't close it I was unable to reopen the disscusion as you advice me to do if I would have problems with the workflow. Leaving me no option but to create a new one. Here is the problem.

Hi, I'm currently using Parse for my Unity application and it's already working on Android and Ios, now we are trying to make it work on Windows phone 8.1, but there is a conflict with the dll files.
System.Threading.Tasks.dll is arleady defined in Parse.Unity.dll and I need to use this same reference in my code. 

Your advice from the other thread was to rebuild the sdk excluding the tasks folder from the project.

But I'm afraid it's going to be more complex than just excluding the Tasks folder in the Parse.unity project, the reference of System.Threading.Taks is being used by the rest of the code and without the classes it can't fulfill the reference. I was able add the reference manually to the same location I'm using from Unity and build the dll, but the same error appears in Unity.

Since I'm not quite experienced in Visual I don't know if I'm loosing something in order to bypass the Task reference.

So again, thanks for Help.

**Comment by richardjrossiii** [comment]
Hey, I've reopened #126. Lets continue discussion there.
