### ISSUE TITLE
Unity Android Parse 1.6.2 throws error: Parse.com Unity AndroidJavaException: java.lang.ClassNotFoundException:com.parse.ParseUnityHelper

### ISSUE THREAD

**Issue by animepauly** [ParsePlatform/Parse-SDK-dotNET#135]
I am not using Parse Push at all and I don't even have a parse Android manifest file in my app, so I am unsure what is trying to access the ParsePushUnityHelper class, but this error is thrown a lot in my app and I can't stop it. I did a search for even a reference to that class in all of my files and can't find any.

**Comment by richardjrossiii** [comment]
Even if you are not using Push, we still require you to include ParsePush.jar (available in the download from Parse.com, or you can compile it from our repo) if you are targeting android via unity.

**Comment by animepauly** [comment]
I can confirm that putting in ParsePush.jar into my project worked, BUT this seems to be extremely problematic if that's the case, because the ParsePush.jar is not included in the Parse Unity SDK. Plus this is not in any documentation that I can find where you have to have that Jar file if you are using Unity and deploying to Android. Please at least put this .jar file in the sdk and put a not in the readme file or something.

**Comment by richardjrossiii** [comment]
@animepauly IIRC it's included in the unity packaging download, but for licensing reasons is/was not in the NuGet distribution or on our website. We may be able to update this in the future.

**Comment by richardjrossiii** [comment]
@animepauly ParsePush.jar will be included with the main SDK deployment in the next release.

**Comment by mehtadakshil** [comment]
Where i can get ParsePush.jar ? I am facing Same issue

**Comment by mehtadakshil** [comment]
from where to download ParsePush.jar !?

**Comment by mehtadakshil** [comment]
I added ParsePush Sdk still Unable to call Start or awake of other Class !
