### ISSUE TITLE
ParseInstallation.CurrentInstallation.SaveAsync() not working when device is not in English.

### ISSUE THREAD

**Issue by meneses-pt** [ParsePlatform/Parse-SDK-dotNET#138]
When I try to call the method:

    ParseInstallation.CurrentInstallation.SaveAsync();

on a phone that is configured with a language other than English

I get an InvalidOperationException: "Cannot change the `timeZone` property of a `_Installation` object."

This occurs because Windows Phone is returning a localized string for the local timezone information. Because that string is localized it won't find a match on the `TimeZoneNameMap` dictionary, thus returning null.

Returning null will make the SDK try to remove the `timeZone` property from the `Installation` object.

*UPDATE*: I was trying to run this in a previous version, so I went and checked if there was a newer version and installed the 1.6.2 version out of NuGet.

This version allows the SDK to set the `timeZone` to null and does not try to remove the property, mostly because you guys changed the `SetIfDifferent` method.
But this raises an exception anyway. When sending the data to the Parse servers I now get "BadRequest", and I think the problem is still the same.

Can you please fix this?

**Comment by richardjrossiii** [comment]
Thanks for the report. I'll look into both parts of this bug (the localized timezone information, and the `SetIfDifferent` bug), and get back to you.

**Comment by bnham** [comment]
So I think the general heuristic should be something like:

# Look up IANA identifier from StandardName => IANA dict. If there's a match, use it. This works for English locales and doesn't lose daylight savings time info.
# If (1) doesn't work, then use the UTC offset do generate the appropriate Etc/* time zone. This loses daylight savings time info, but what can you do.
# If there is a non-zero minute offset in (2), then use this mapping: UTC-09:30 => Pacific/Marquesas, UTC-04:30 => America/Caracas, UTC-03:30 => Canada/Newfoundland, UTC+03:30 => Asia/Tehran, UTC+04:30 => Asia/Kabul, UTC+05:30 => Asia/Kolkata, UTC+05:45 => Asia/Kathmandu, UTC+06:30 => Asia/Rangoon, UTC+08:30 => Asia/Pyongyang, UTC+08:45 => Australia/Eucla, UTC+09:30 => Australia/Adelaide, UTC+10:30 => Australia/Lord_Howe, UTC+12:45 => Pacific/Chatham

For the record here are the Etc/* time zones that we support. None of them have minute offsets. We don't make this up, it's just from the IANA time zone list and I don't think the server should accept non-IANA time zones.

```
GMT    GMT+1   GMT-12  GMT+2  GMT-5  GMT+7  Greenwich
GMT0   GMT-10  GMT+12  GMT-3  GMT+5  GMT-8  UCT
GMT-0  GMT+10  GMT-13  GMT+3  GMT-6  GMT+8  Universal
GMT+0  GMT-11  GMT-14  GMT-4  GMT+6  GMT-9  UTC
GMT-1  GMT+11  GMT-2   GMT+4  GMT-7  GMT+9  Zulu
```

FWIW, even third party libraries that try to help you with this need to guess. It looks like the correct thing to do would be to use the Id property on TimeZoneInfo as the key into the map but that doesn't work on PCL devices like WP8, so you just have to use StandardName and guess, as Noda Time does: https://github.com/nodatime/nodatime/blob/master/src/NodaTime/TimeZones/TzdbDateTimeZoneSource.cs#L198-L222.

**Comment by inlined** [comment]
Oh man, it's been years since I ran into this. Adding some historic context since I'm no longer at Parse. If I recall correctly, the methods for asking for the locale-neutral (aka en-US) time zone is not available in WinRT so you can't do it reliably in a portable binary. The temporary fix was to change the current thread's locale temporarily to locale-insensitive, but this threw a security error on Windows Mobile. The "correct" solution was to create a (non-winRT) DLL for each windows platform which would expose the locale-insensitive name that mapped to a TZ-database name which captures daylight savings info, but this API call alone didn't seem to meet the minimum bar for complicating the Parse SDK deployment story.

**Comment by meneses-pt** [comment]
Well, I have a solution that I have used in a project of mine, using TimeZones because of the exact same problem.

If you feel like trying it, go ahead. Also if you have questions, please feel free to ask.

```c#

public static string GetDeviceTimeZone()
{
	var timezone = "Etc/GMT";

	try
	{
		var currentTime = DateTime.Now;
		var currentUtcTime = TimeZoneInfo.ConvertTime(currentTime, TimeZoneInfo.Utc);
		var currentOffset = Offset.FromHours((currentTime - currentUtcTime).Hours);
		var currentInstant = new Instant(currentTime.Ticks);

		var timeZonesList = TzdbDateTimeZoneSource.Default.ZoneLocations;

		for (int i = 0; i < 52; i++)
		{
			var laterTime = currentTime.AddDays(7*i);
			var laterUtcTime = TimeZoneInfo.ConvertTime(laterTime, TimeZoneInfo.Utc);
			var laterOffset = Offset.FromHours((laterTime - laterUtcTime).Hours);
			var laterInstant = new Instant(laterTime.Ticks);
			var tzdb = DateTimeZoneProviders.Tzdb;

			var list =
				from location in timeZonesList
				let zoneId = location.ZoneId  
				let tz = tzdb[zoneId]
				let currentOffsetTemp = tz.GetZoneInterval(currentInstant).WallOffset
				let laterOffsetTemp = tz.GetZoneInterval(laterInstant).WallOffset
				where currentOffsetTemp.Ticks == currentOffset.Ticks
				where laterOffsetTemp.Ticks == laterOffset.Ticks
				select location;

			var tzdbZoneLocations = list as TzdbZoneLocation[] ?? list.ToArray();
			if (!tzdbZoneLocations.Any())
			{
				continue;
			}

			timeZonesList = new List<TzdbZoneLocation>(tzdbZoneLocations);
		}

		var finalList =
			from location in timeZonesList
			let zoneId = location.ZoneId
			select new
			{
				Id = zoneId,
				DisplayValue = zoneId
			};

		var localTimeZones = finalList.ToDictionary(x => x.Id, x => x.DisplayValue);

		return localTimeZones.FirstOrDefault().Value ?? timezone;
	}
	catch (Exception exception)
	{
		Debug.WriteLine(exception);
	}

	return timezone;
}

```

**Comment by inlined** [comment]
Well, I'm unlikely to contribute to the Parse SDK anymore since I now work at Firebase. If you end up with any timezone in the [TZ-database](https://en.wikipedia.org/wiki/Tz_database) you'll get support for local push delivery times. Try to get ones like America/Los_Angeles, which capture DST rules so you don't end up with customers getting notifications at the wrong between a DST transition and the next time they open the app.

**Comment by richardjrossiii** [comment]
@inlined @meneses-pt I have a solution locally that should cover all of these use-cases, it will be public within a few hours after some additional testing (testing the north Korean timezone is surprisingly difficult).

Thanks for all of your input.
