### ISSUE TITLE
What changed in 1.7.0?

### ISSUE THREAD

**Issue by andymads** [ParsePlatform/Parse-SDK-dotNET#151]
The changelog here https://parse.com/docs/downloads does not give details for 1.7.0.

**Comment by richardjrossiii** [comment]
@andymads Thanks for the report, it will be fixed by end of day.

For future reference, the source of truth for all of our releases is now [here on GitHub](https://github.com/ParsePlatform/Parse-SDK-dotNET/releases), which will always contain the updated release notes.
