### ISSUE TITLE
input JSON was invalid

### ISSUE THREAD

**Issue by f1lander** [ParsePlatform/Parse-SDK-dotNET#156]
HI, I've this error when I try to get object from parse cloud, It's worked but now just started to get this error.

This is my code:
    var query = ParseObject.GetQuery("Travels");          
    var results = await query.FirstAsync();

The catch error send me "Invalide repsonse from server" and the innerException "input Json was invalid"

I work in WP8 app (.net)

Thanks!

**Comment by prathmeshnaik91** [comment]
I am facing the same issue in windows phone 8. When i use this snippet for initialization `ParseClient.Initialize("Application Id", "dot net key"); ` it is working fine but now i am hosting parse server on my local and using  ```
ParseClient.Initialize(new ParseClient.Configuration
            {
                ApplicationId = "Application Id",
                WindowsKey = "dot net key",
                Server = "http://10.0.10.77:1337/parse",
            });
```  in this case i am facing issue, 

> The catch error send me "Invalide repsonse from server" and the innerException "input Json was invalid"

Regarding parse server i am able to save and retrieve data from it properly using parse rest. So i feel there is no issue in parse server and something wrong with sdk.

 .

**Comment by richardjrossiii** [comment]
@prathmeshnaik91 Sorry, we need better documentation on this. You should add a trailing slash past your URL (e.g. `http://10.0.10.77:1337/parse/`), and it should work as expected.

**Comment by prathmeshnaik91** [comment]
@richardjrossiii thanks its working now (y). I have also proposed change regarding this in git documentation.

**Comment by vip32** [comment]
oh my, that / resolved the issue
