### ISSUE TITLE
Error when trying to build to WebGL from the UnusedBytCodeStripper

### ISSUE THREAD

**Issue by animepauly** [ParsePlatform/Parse-SDK-dotNET#157]
When I try to build to WebGL, I get this error that prevents me from doing so:

Failed running /Applications/Unity/Unity.app/Contents/Frameworks/Tools/UnusedByteCodeStripper2/UnusedBytecodeStripper2.exe -out "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/tempStrip" -l none -c link -b False -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Core.xml" -f "/Applications/Unity/Unity.app/Contents/Frameworks/il2cpp/LinkerDescriptors" -x "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/methods_pointedto_by_uievents.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/AI.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Animation.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Audio.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/CloudWebServices.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Core.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/IMGUI.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/JSONSerialize.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/ParticleSystem.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/ParticlesLegacy.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Physics.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Physics2D.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Terrain.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/TerrainPhysics.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/TextRendering.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/UI.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/UNET.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/UnityAds.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/UnityAnalytics.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/UnityConnect.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/UnityWebRequest.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/VR.xml" -x "/Applications/Unity/PlaybackEngines/WebGLSupport/Whitelists/Web.xml" -x "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Assets/link.xml" -x "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Assets/scripts/link.xml" -d "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed" -a  "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/Assembly-CSharp-firstpass.dll" -a  "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" -a  "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/Assembly-UnityScript-firstpass.dll" -a  "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/Assembly-UnityScript.dll" -a  "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/UnityEngine.UI.dll" -a  "/Users/paulborawski/www/adquizition/adquiz_app_unity/quizapp/Temp/StagingArea/Data/Managed/Parse.Unity.dll"

stdout:
Fatal error in Mono CIL Linker
System.Exception: Error processing method: 'System.Void Parse.PlatformHooks/<>c__DisplayClass28::<RegisterDeviceTokenRequest>b__26()' in assembly: 'Parse.Unity.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Byte[] UnityEngine.iOS.NotificationServices::get_deviceToken()
  at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x00000] in <filename unknown>:0 
  at Mono.Linker.Steps.MarkStep.Process () [0x00000] in <filename unknown>:0 
  at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Driver.Run () [0x00000] in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriverWithErrorHandling (Mono.Linker.Driver driver) [0x00000] in <filename unknown>:0 
  at Mono.Linker.Driver.RunDriver (Mono.Linker.Driver driver) [0x00000] in <filename unknown>:0 
stderr:

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:94)
UnityEditorInternal.AssemblyStripper:RunAssemblyLinker(IEnumerable`1, String&, String&, String, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:107)
UnityEditorInternal.AssemblyStripper:StripAssembliesTo(String[], String[], String, String, String&, String&, String, IIl2CppPlatformProvider, IEnumerable`1, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:100)
UnityEditorInternal.AssemblyStripper:RunAssemblyStripper(String, IEnumerable, String, String[], String[], String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:201)
UnityEditorInternal.AssemblyStripper:StripAssemblies(String, IIl2CppPlatformProvider, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/AssemblyStripper.cs:131)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:201)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry, Boolean) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:135)
UnityEditor.HostView:OnGUI()

I haven't messed with the link.xml so not sure what the problem could be. I am using Parse SDK 1.7.0 and Unity Pro 5.3.1f1

Here is the link.xml for info:

<linker>
  <assembly fullname="UnityEngine">
    <type fullname="UnityEngine.iOS.NotificationServices" preserve="all"/>
    <type fullname="UnityEngine.NotificationServices" preserve="all"/>
    <type fullname="UnityEngine.AndroidJavaClass" preserve="all"/>
    <type fullname="UnityEngine.AndroidJavaObject" preserve="all"/>
  </assembly>

  <assembly fullname="Parse.Unity">
    <namespace fullname="Parse" preserve="all"/>
    <namespace fullname="Parse.Internal" preserve="all"/>
  </assembly>
</linker>

**Comment by richardjrossiii** [comment]
We do not currently support WebGL as a target for Unity.

Please note that internally, we are working *extremely* hard to get this to a working state, and it will hopefully be ready at some point before the end Q1 2016. Its a lot harder than it looks, due to some issues with multithreading, assembly stripping (as you have discovered) amongst other things.

**Comment by animepauly** [comment]
Oh ok, thanks! I thought I read somewhere that people got it working.

**Comment by Apoll0** [comment]
Hello!
Do you still work with WebGL compatibility?
Or this functionality will be never done?

**Comment by hunterua** [comment]
Hi!
Is this issue is solved ?

**Comment by hl4hck** [comment]
Hello!
How is it going?
