### ISSUE TITLE
WindowsKey instead of ClientKey

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/Parse-SDK-dotNET#170]
Hi,

I try to get the latest parse from here and also the official website and i found that the ParseClient.Configuration only provide WindowsKey instead of ClientKey, is that the same thing?

and the Migration steps shows that it should be ClientKey from the link here
https://parse.com/docs/server/guide#installation

Thank you.

**Comment by kenglou** [comment]
no body answering the qs?

**Comment by hallucinogen** [comment]
Hi there,

Thanks for the report. The docs was wrong and I have fixed it (waiting for deploy). In .NET the `Configuration` only accepts `WindowsKey` which is .NET key that you can get from the dashboard:

<img width="691" alt="screen shot 2016-02-01 at 9 07 19 am" src="https://cloud.githubusercontent.com/assets/681920/12724741/287a5a52-c8c4-11e5-931f-63dff91667b8.png">

<img width="1139" alt="screen shot 2016-02-01 at 9 07 51 am" src="https://cloud.githubusercontent.com/assets/681920/12724744/2bc77604-c8c4-11e5-8a9e-9b449f15edeb.png">
