### ISSUE TITLE
How to set up Parse Backend

### ISSUE THREAD

**Issue by sankp** [ParsePlatform/Parse-SDK-dotNET#171]
Hello,

I am using parse for my small personal application. Now just news came out about Parse is going to stop services after one year and as Parse SDK is open source now. Is there any way to set up backend by ourselves now. If yes then is there any guidelines available to start with ? I have a phonegap app in which i sends push notification from .net. If i want to use direct SDK from here without Parse service. Is that possible ?

**Comment by hallucinogen** [comment]
Hi @sankp,

You will want to check out our open-sourced Parse Server here: https://github.com/ParsePlatform/parse-server. The server is compatible with our SDKs (including Parse .NET SDK). The only thing to do from the SDK side is to change the `Configuration.Server` (https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/Parse/Public/ParseClient.cs#L129) into your own hosted Parse Server.

Further question can be asked in Parse Server repo.

Hope it helps!
