### ISSUE TITLE
[Parse Server] clientKey is optional if using Parse Server

### ISSUE THREAD

**Issue by hramos** [ParsePlatform/Parse-SDK-dotNET#183]
A client key (or dotNetKey) does not need to be configured in order to deploy a Parse Server. The Parse .NET SDK does not currently support connecting to a clientKey-less Parse Server.

To resolve this, a new initialization method is required:

`public static void Initialize(string applicationId) { ...`

We should also remove any exceptions that may be thrown if a client key is not provided.

**Comment by richardjrossiii** [comment]
This is a non-issue. If you wish to point to a parse-server instance, you should use the version of `Initialize` with a `ParseClient.Configuration` object, like so:

    ParseClient.Initialize(new ParseClient.Configuration {
         ApplicationId = "key",
         Server = "server url"
    });
