### ISSUE TITLE
HttpClient.Portable.cs bug

### ISSUE THREAD

**Issue by rihadavid** [ParsePlatform/Parse-SDK-dotNET#186]
I believe that ParseCommon/Internal/HttpClient/Portable/HttpClient.Portable.cs is missing `if (data != null)` on line 56.

Calling `message.Content = new StreamContent(data);` when data is null causes exception.

ParseCore/Internal/Query/Controller/ParseQueryController.cs FindAsync() is calling `commandRunner.RunCommandAsync(command, ..)` with command data explicitly set to null and command method GET. Setting `data = new MemoryStream(new byte[0]);` would not help because GET method must not have data.

```
if (data != null)
                message.Content = new StreamContent(data);
```

solves the problem.

**Comment by richardjrossiii** [comment]
Yep, you're correct. I have this change on one of my local branches, but please, submit a PR to patch it, we definitely accept external contributions!
