### ISSUE TITLE
MAC OS (Xamarin) no build

### ISSUE THREAD

**Issue by Avatarchik** [ParsePlatform/Parse-SDK-dotNET#189]
error
.../Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj: error : .../Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj: .../Parse-SDK-dotNET-master/AssemblyLister/AssemblyLister.UWP/AssemblyLister.UWP.csproj could not import "$(MSBuildExtensionsPath32)\Microsoft\Portable\$(TargetFrameworkVersion)\Microsoft.Portable.CSharp.targets"

**Comment by richardjrossiii** [comment]
Duplicate of #88
