### ISSUE TITLE
Unable to compile with Xamarin

### ISSUE THREAD

**Issue by VennSteve** [ParsePlatform/Parse-SDK-dotNET#191]
I'm having an impossible time trying to compile this on my Mac with Xamarin. The instructions say just use xbuild parse.sln but both that and the IDE are giving me the errors: 

Parse-SDK-dotNET/ParseCommon/Properties/AssemblyInfo.cs(7,7): Error CS0246: The type or namespace name `Parse' could not be found. Are you missing an assembly reference? (CS0246) (ParseCommon.Portable)

and similarly

Parse-SDK-dotNET/ParseCommon/Properties/AssemblyInfo.cs(7,7): Error CS0246: The type or namespace name `Parse' could not be found. Are you missing an assembly reference? (CS0246) (ParseCommon.Unity)

Seems like there is an error with the way the current version is setup in the repository but I'm not sure what to do about it.

**Comment by richardjrossiii** [comment]
As discussed previously, there's an issue with now xbuild handles search paths compared to MSBuild.

We don't currently support compiling the SDK in any environment other than Visual Studio, sorry (though the community edition plus a VM should work fine).

https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-182609656
