### ISSUE TITLE
How to forbid parse sdk from saving info to the collection "Installastion"?

### ISSUE THREAD

**Issue by huang1196** [ParsePlatform/Parse-SDK-dotNET#197]
Hi, we do not want to upload the data like deviceToken, version to the collection 'Installation' by parse sdk. We are recording these info by our own ways.

How to stop it?

**Comment by richardjrossiii** [comment]
We don't currently have any way of disabling this information, other than simply forking the SDKs and removing the associated logic, which you are more than welcome to do.
