### ISSUE TITLE
Is Parse DotNet SDK and Unity SDK is still under support?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/Parse-SDK-dotNET#198]
I wish to know that what's coming up next after Parse-Server is announced and the Parse.com is shutting down soon. 

As currently I found there is a bug for my Unity3d Project as after I update my Parse SDK to newer version, the saveAsync functions seems like will hang my UI for a while before my user.saveAsync function. Is anyone experience this before?

**Comment by richardjrossiii** [comment]
Firstly, Parse is not dead (yet). We are committed to supporting parse.com and the parse platform until the shutdown date is reached.

Parse-server and the client SDKs will live on indefinitely, and we have no current plans to stop working on them (in fact, we just rolled out a new feature for parse-server today: http://blog.parse.com/announcements/parse-server-goes-realtime-with-live-queries/)

It's possible that there is an issue with `SaveAsync` in the current version of the SDK, though we haven't gotten any reports on it. If you could open another issue with more details on that specific use-case, that would be great.
