### ISSUE TITLE
FormatException: Input string was not in the correct format at Parse.Internal.HttpClient > GetStatusCode

### ISSUE THREAD

**Issue by animepauly** [ParsePlatform/Parse-SDK-dotNET#20]
Using Parse Unity SDK 1.6.0 and Unity 5.2.1

When my app doesn't have internet connectivity and the app is trying to fetch data using FetchAsync(), I am getting the error "FormatException: Input string was not in the correct format" at Parse.Internal.HttpClient > GetStatusCode every time. 

I am trying to write functionality if fetching of data fails, I test internet connectivity and if the connection is good, I ask the user to try and fetch the data again, and if the connection is not good I ask them to check their internet connection. That works if I am connected to the Internet but if I am not I get this error, I never get to the internet connection test, and my code stays in the following loop forever

```
ParseUser __parseUser = __dataObj as ParseUser;
var __fetchObjTask = __parseUser.FetchAsync();

Debug.Log ("FetchData::fetching parse User!");
//The CODE SITS IN THIS WHILE LOOP FOREVER SINCE IT'S NEVER COMPLETE
//AND I CANNOT CHECK FOR IS FAULTED OR ISCANCELED AS THOSE ARE FALSE IN THE WHILE LOOP
while (!__fetchObjTask.IsCompleted)
{
	Debug.Log ("FETCHING USER DATA!");
	Debug.LogWarning("__fetchObjTask.IsCanceled = "+__fetchObjTask.IsCanceled);
	Debug.LogWarning("__fetchObjTask.IsFaulted = "+__fetchObjTask.IsFaulted);
	yield return null;
}
Debug.Log ("TASK COMPLETED!");
Debug.LogWarning("__fetchObjTask.IsCanceled = "+__fetchObjTask.IsCanceled);
Debug.LogWarning("__fetchObjTask.IsFaulted = "+__fetchObjTask.IsFaulted);
if (__fetchObjTask.IsCanceled || __fetchObjTask.IsFaulted)
{
	Debug.LogWarning("THERE WAS A PROBLEM FETCHING DATA!");
	Debug.LogWarning("FetchData::Error message " + __fetchObjTask.Exception.Message);
}
```

I have been using Parse for over a year and have not seen this until the latest update, so not sure what got changed but I can't seem to figure out how to catch this error.

**Comment by richardjrossiii** [comment]
Thanks for the report. This sounds strange, we'll look into it.

**Comment by animepauly** [comment]
Great, thanks!

**Comment by animepauly** [comment]
Is this fixed in the Unity SDK then, do I download the update from this repo, or do I have to wait until you update the SDK in Parse?

**Comment by hallucinogen** [comment]
You'll have to wait until 1.6.1 build which should  happen sometime around next week.
