### ISSUE TITLE
Logout Anonymous User will delete the session token?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/Parse-SDK-dotNET#200]
Hi,

If let's say i logout an anonymous user from Parse DotNet, my session in Parse.com will be deleted. What should i do if i do not want to delete the annoymous session? 

I wish to be able to relogin using the same key for anonymous user from different mobile devices, in GooglePlay I'll use the GooglePlay Game Service to save the "KEY", and when player logout 1 google play service, he/she should be able to login with a different Key and have the power of Switch User ability. Is this possible by using anonymous user login?

THank you.

**Comment by richardjrossiii** [comment]
Your only solution would be to use [parse-server](https://github.com/ParsePlatform/parse-server) and create a custom auth handler for your user, that can generate a key for your user and allow the recovering of that user for you.

Anonymous users, by definition, cannot be recovered unless you have another authentication method linked to them, however.
