### ISSUE TITLE
Receiving IntentService[ParsePushService] at start

### ISSUE THREAD

**Issue by jenissimo** [ParsePlatform/Parse-SDK-dotNET#202]
After adding ParsePush.jar to Unity project app crash with

    04-16 11:55:16.694 16968-17163/com.triclops.hotlava E/AndroidRuntime: FATAL EXCEPTION:     IntentService[ParsePushService]
                                                                      Process: com.triclops.hotlava, PID: 16968
                                                                      java.lang.Error: FATAL EXCEPTION   [IntentService[ParsePushService]]
                                                                      Unity version     : 5.3.1f1
                                                                      Device model      : ZTE ZTE T660
                                                                      Device fingerprint: ZTE/P635A20/P635A20:5.0.2/LRX22G/20150915.114212:user/release-keys

I am already tried this steps, but it wasn`t help:
https://github.com/playgameservices/play-games-plugin-for-unity/issues/939

**Additional info:**
[AndroidManifest.txt](https://github.com/ParsePlatform/Parse-SDK-dotNET/files/222116/AndroidManifest.txt)
[log.txt](https://github.com/ParsePlatform/Parse-SDK-dotNET/files/222115/log.txt)

**Comment by richardjrossiii** [comment]
Any chance you can provide us with a stack trace or a project that reproduces the crash? Otherwise there's not much more I can investigate from what you've given.
