### ISSUE TITLE
unchangable URL in dll

### ISSUE THREAD

**Issue by wootangs** [ParsePlatform/Parse-SDK-dotNET#208]
We are working on Unity 4.7 and we are using Facebook 6.2.2 and Parse 1.5.3.0
During DB and server migration to Heroku, the issue is that we can't change server url because it's in dll.

ParseClient.Initialize(new ParseClient.Configuration {
ApplicationId = "YOUR_APP_ID",
Server = "http://localhost:1337/parse/“
});

public static void Initialize(string applicationId, string dotnetKey)
{
object obj;
Monitor.Enter(obj = ParseClient.mutex);
try
{
ParseClient.HostName = (ParseClient.HostName ?? new Uri("https://api.parse.com/"));
ParseClient.ApplicationId = applicationId;
. . .
}
finally
{
Monitor.Exit(obj);
}
}

Is there any solution to change url in the lower version 1.5.3.?
This is so important issue for migration.

**Comment by richardjrossiii** [comment]
No, there is no way to change the server URL string in previous versions of the SDK. I would strongly recommend updating to a later version of the SDK.
