### ISSUE TITLE
Local Datastore

### ISSUE THREAD

**Issue by Navideck-fotis** [ParsePlatform/Parse-SDK-dotNET#209]
Can we expect "Local Datastore" as iOS & Android SDKs already support?

**Comment by richardjrossiii** [comment]
No. Local datastore, while a cool feature, has been deemed as a 'fundamentally flawed' model of persistence. The main issues come with maintenance - our model of recursively persisting objects inside of a pin, while having a single source of truth for the storage of that object have led to making it impossible to scale use cases that are more complex than a basic object-graph.

The parse team has decided as such (and for other reasons, mostly relating to maintenance), that it is a failed experiment, and we are not currently pursuing it further.

**Comment by Navideck-fotis** [comment]
@richardjrossiii wow, I had no idea. Thanks for letting us know.
