### ISSUE TITLE
Change in IList<> behavior

### ISSUE THREAD

**Issue by jrlee-pw** [ParsePlatform/Parse-SDK-dotNET#216]
I am using Parse in a Unity project. As part of the migration process, I cloned Parse-SDK-dotNET 1.7, and made a minor modification to allow me to specify the server URI. Previously, I was using Parse.Unity.dll v1.5.5.

This introduced a behavioral change for properties of derived ParseObject classes where the property is an IList<> type. Formerly, if I added or removed items from the list, it would be sufficient to dirty the list, and the change would be reflected in the database when I saved the object; now, I have to touch the IList<> object itself to dirty the list. (See example below)

Is this change by design? It is a problem, as it is a breaking change. Could it be due to a mistake I made in building the assembly? Or some other configuration issue? Or...? 

Thanks for the consideration.

`    [ParseClassName( "ThingHolder" )]
    class ThingHolder : ParseObject
    {
        [ParseFieldName( "myThing" )]
        public IList<ParseObject> MyThings
        {
            get { return GetProperty< IList<ParseObject> >( "myThing" ); } 
            private set { SetProperty( value, "myThing" ); }
        }

        public void AddAThing1( ParseObject thing )
        {
            MyThings.Add( thing );	// This used to be sufficient - Parse.Unity.dll (1.5.5)
            SaveAsync();
        }

        public void AddAThing2( ParseObject thing )
        {
            MyThings.Add( thing );
            MyThings = MyThings;	// Now this is necessary! - Parse.Unity.dll (1.7.0)
            SaveAsync();
        }
    }
`

**Comment by richardjrossiii** [comment]
This was intentional, and part of #66. You can read the rationale there.
