### ISSUE TITLE
 ParseClient.MasterKey internal by design?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/Parse-SDK-dotNET#219]
I was trying to figure out a way to send a master key with API requests.  I see that  ParseClient.MasterKey exists, but it's internal.  I know using AdditionalHTTPHeaders to send a X-Parse-Master-Key header is an option, but that seems like a kludge.  Is ParseClient.MasterKey marked as internal by design?

**Comment by richardjrossiii** [comment]
Yes. It primarily exists for the use-case of our internal testing, as we didn't initially see it as super valuable to expose to apps (there's a lot of damage that a leaked master key can do).

**Comment by AndrewLane** [comment]
thanks
