### ISSUE TITLE
Parse 1.6.0 Unity: get_bundleIdentifier can only be called from the main thread.

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-dotNET#22]
Hi, after upgrading to the 1.6.0 SDK for Unity, I'm getting this error after calling a CloudCode method

Full exception:

	ArgumentException: get_bundleIdentifier can only be called from the main thread.
	Constructors and field initializers will be executed from the loading thread when loading a scene.
	Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
	System.Reflection.MonoProperty.StaticGetterAdapterFrame[String] (System.Reflection.StaticGetter`1 getter, System.Object obj) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoProperty.cs:239)
	System.Reflection.MonoProperty.GetValue (System.Object obj, System.Object[] index) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoProperty.cs:295)
	Parse.PlatformHooks.get_AppDisplayVersion ()
	Parse.Internal.ParseCommand..ctor (System.String relativeUri, System.String method, System.String sessionToken, IList`1 headers, System.IO.Stream stream, System.String contentType)
	Parse.Internal.ParseCommand..ctor (System.String relativeUri, System.String method, System.String sessionToken, IList`1 headers, IDictionary`2 data)

**Comment by hallucinogen** [comment]
Thank you for your report! This will be fixed in #15.
