### ISSUE TITLE
Only first save of CurrentInstallation works when custom columns are added

### ISSUE THREAD

**Issue by miracle7** [ParsePlatform/Parse-SDK-dotNET#221]
When I run the following code the first time, the installation is saved successfully.
```
var installation = ParseInstallation.CurrentInstallation;
installation["language"] = Localization.language;
installation.SaveAsync();
```
All subsequent times it fails with the error:
`Parse.ParseException: at least one ID field (deviceToken, installationId) must be specified in this operation`

If I omit the second line where I set the language column I can save as many times as I like without issues. I have also tried doing things like fetching the current installation before saving it but with no success.

The installation does have an 'installationId' field set at all times, so basically out of ideas of why this is happening, especially only when setting a custom column.

![image](https://cloud.githubusercontent.com/assets/5317556/17048145/fc4897d8-5026-11e6-96b1-247cebd75859.png)

If anyone could help me fix or workaround this problem it would be greatly appreciated as it is holding up our development :)

**Comment by miracle7** [comment]
I am not sure whether this is a problem with parse server or the dot net sdk, but I noticed that both myself and another user on the parse server github were experiencing this issue using the dot net sdk which is why I made this issue:

More information such as logs from parse server are available here:
https://github.com/ParsePlatform/parse-server/issues/2090

**Comment by richardjrossiii** [comment]
@miracle7 A Parse.ParseException is almost certainly a backend issue. There's no logic inside ParseInstallation to my knowledge that would cause such an error to occur.
