### ISSUE TITLE
Parse SDK sending POST instead of GET when trying to fetch objects

### ISSUE THREAD

**Issue by peterwilli** [ParsePlatform/Parse-SDK-dotNET#222]
Hi There,

I am trying to integrate the build posted here: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-217977259

I am having issues with fetching a list of objects, I do it like this:

	var query = ParseObject.GetQuery("HiScore").Limit(100).OrderByDescending("score").WhereGreaterThanOrEqualTo("createdAt", time);

	query.FindAsync().ContinueWith(t => {
		IEnumerable<ParseObject> scores = t.Result;
		cache.Clear();

		if(scores != null) {
			// Map the scores to ScoreEntry objects
			foreach(ParseObject score in scores) {
				if(Manager.debug) Debug.Log ("Parse loop -> " + score["coins"] + " - " + score["kills"] + " - " + score["nickName"]);
			}
		}
	});

But I dont get any kind of reply or callback in this example. What's weirder is that my Server logs tell me this:

	141.101.x.x - - [27/Jul/2016:10:10:52 +0200] "POST /parse/classes/HiScore?order=-score&limit=100 HTTP/1.1" 301 178 "-" "UnityPlayer/5.3.6f1 (http://unity3d.com)"

It is doing a POST request while I THINK it should be doing a GET request (because I try to find objects)

Is there anyone who know what's going on? Thanks!

**Comment by amplebrain** [comment]
Fetching a list seems to work fine for me. Posted my code snippet below if that helps

`
		IEnumerable<ParseObject> leaders = new List<ParseObject>();

		ParseQuery<ParseObject> parseData = ParseObject.GetQuery ("GameName").OrderByDescending ("HighScore").Limit(10);
		Task queryTask = parseData.FindAsync().ContinueWith (t => {
			leaders = t.Result;

		});

		while (!queryTask.IsCompleted) yield return null;

		if (queryTask.IsFaulted) {
			//Data Unreachable; Show Last stored Leaderboard
		}
		else if (!queryTask.IsCanceled) {

                    //Do Something with retrieved Leaderboard here
		} 
`

I am using a forked version of the 1.7 Unity SDK and parse-server. 

What version of the SDK are you using?

**Comment by peterwilli** [comment]
@amplebrain Hi there, I didn't have the luxury of building the SDK myself (humble linux user) so some good people have done it for me, see: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-217832665 and https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166#issuecomment-217834669 

Neither worked for me, I'll try your example soon, maybe it will work suddenly :)

**Comment by peterwilli** [comment]
@amplebrain really weird, but today I'm not managing to even fetch anything at all! Gosh, ever since parse went down it's nothing but trouble for me. I never managed to get the server and the unity client to work with eachother. It's a disaster and am considering rolling my own backend since it's just 1 project using parse :(

**Comment by amplebrain** [comment]
What error does Unity throw? Can you try to catch the ParseExceptions and see if they tell you anything?

What version of parse server are you running? 
Do you get any response when you try to CURL? 
Can you post your server config here?

So far, parse-server has been fairly stable my test deployment but I havent migrated most of my users yet.

**Comment by peterwilli** [comment]
@amplebrain It doesnt even request anything at all. It used to work a little (as in: I could see the Unity SDK doing requests to my server).

But none of it matters now as I rolled my own simple PHP script and replaced Parse functions with simple use of WWW objects to make requests to them.

I know it's not really solving the problem but at least now I know for sure it works. I just didn't want to spend any more hours on it.

But thanks for the help, I'm glad it works for you! :)
