### ISSUE TITLE
Support for Xamarin component?

### ISSUE THREAD

**Issue by CatherineSD** [ParsePlatform/Parse-SDK-dotNET#228]
Hi,
We are currently using the Parse component in our app in Xamarin and it is working great! We are facing an issue that seems to have a fix already (https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/106) but it is not fixed in the component. Other issues might have been fixed already but not yet in the component.

Does anyone know if this component will still be maintained in the future? Or who I can contact to request an update of the component?

Thanks for any info on the subject!

**Comment by richardjrossiii** [comment]
No, at this time we are no longer maintaining components in the Xamarin Store, Unity Store, or other package managers. The source of truth for all version of the SDK is here on github, and we encourage you to download and install it from the releases page https://github.com/ParsePlatform/Parse-SDK-dotNET/releases
