### ISSUE TITLE
IPv6 support ? Apps being rejected by Apple

### ISSUE THREAD

**Issue by kitkat14** [ParsePlatform/Parse-SDK-dotNET#234]
Did anyone test this on a IPv6 network. 
I think it doesn't work because Apple is blow rejecting apps without IPv6 support. And they can't reach login...

(Using Xamarin to build iOS app)

**Comment by kitkat14** [comment]
Some solution here ?

**Comment by richardjrossiii** [comment]
There's nothing in our network stack that relies on any version of IP, whatsoever. If you're experiencing a problem, it's probably not on us (I just tested on my IPv6 network, and everything appears to be in order).

Is it perhaps a firewall issue?

**Comment by kitkat14** [comment]
I have no idea. Apple review team is not able to login or register. I am not doing anything special just normal login/register that works on my networks. But they said it's probably something with ipv6. So I have no idea what could be the problem only that the sdk is not IPv6 ready.

**Comment by richardjrossiii** [comment]
Assuming you're using parse-server, is it possible that your host is not configured for IPv6 yet? And if you're not using parse-server, we **very** strongly encourage you to migrate ASAP.

**Comment by kitkat14** [comment]
I was using parse server before but because the sdk is not updated to work with gcm push I had to revert back to using plain old parse. 

So we are talking about parse native host.

**Comment by richardjrossiii** [comment]
http://api.parse.com does not support IPv6, and will never support IPv6. If you need IPv6 support, please migrate to parse-server.

**Comment by kitkat14** [comment]
Thanks for letting me know. 
Will drop this parse all together and migrate to firebase or AWS. Too much hassle with all these parse bugs. Thanks for the trouble

**Comment by lacker** [comment]
I suggest Firebase. Good luck!
