### ISSUE TITLE
ParseCloud.CallFunctionAsync doesn't always return

### ISSUE THREAD

**Issue by santacrs** [ParsePlatform/Parse-SDK-dotNET#25]
We are noticing sometimes that ParseCloud.CallFunctionAsync doesn't always return when internet is bogged down or reception is low on the device. The cloud call works most of the time but it does just sit there forever on occasions. One the app is restarted then it start functioning again. 

The function we are calling is just returning static data from some tables so the amount of data and time to retrieve data is always the same so it shouldn't be triggering an internal time out. But even if it does, it should eventually through an exception, return blank or time out rather than just sit there indefinitely. 

Is this is a bug with the Parse Unity SDK?

**Comment by richardjrossiii** [comment]
Seems to me like this is a bug in Unity's network stack, as we don't do anything specific related to network connectivity in the SDK.

If you can provide some example code that shows us that this issue is in our SDK and not Unity's, I'd be glad to help. Otherwise, there's unfortunately not much we can do.

**Comment by santacrs** [comment]
It's a concern that for some users the app will remain on a loading screen indefinitely.  We will attempt to implement our own timeout checks for calls we find it occurs on. We plan on reattempting the call after 10 seconds if the return function is not reached in that time frame. Time will tell if it resolves the issue as it is difficult to reproduce. However, there are many locations this may occur on in the future. Is there any such timeout logic implemented in the Parse Unity API's server cloud call CallFunctionAsync?

**Comment by santacrs** [comment]
So far the time out check we added seems to have resolved the issue. It would be great if this was implemented as part of the SDK so the I don't have to add this time out logic for each CallFunctionAsync call that we make in the code. If just basically reattempts the call if more than 10 seconds pass without the callback function being triggered.

**Comment by richardjrossiii** [comment]
@santacrs I'm not sure how we can do that, as each of our REST requests that we make are intended to have side-effects (and cannot be easily cancelled/reverted), re-sending the request could cause a lot of unforeseen issues.

I would strongly suggest filing a bug with the Unity folks instead, as it seems there's a fundamental flaw with their underlying web request library.

**Comment by santacrs** [comment]
I can't speak to the underlying cause.

I can see an automatic reattempt being an issue if it's modifying data but if it's retrieving data as we are it either returns the data or it doesn't. A safer option is just have it force the callback with an exception/error state if the timeout occurs and then the developer can handle the scenario as needed.
