### ISSUE TITLE
Cross-thread access exception on the UI thread on Xamarin.iOS

### ISSUE THREAD

**Issue by johnthiriet** [ParsePlatform/Parse-SDK-dotNET#33]
There's a UI cross-thread access exception silently happening on iOS.

I managed to fix the issue locally by modifying the following code :

From 
    public Task ExecuteParseInstallationSaveHookAsync(ParseInstallation installation) {
      return Task.Run(() => {
        installation.SetIfDifferent("badge", installation.Badge);
      });

To 

    public async Task ExecuteParseInstallationSaveHookAsync(ParseInstallation installation) {    
		installation.SetIfDifferent ("badge", installation.Badge);
    }

I try to make a pull request but I don't have the necessary rights for it.
Please fix the issue as it renders Push on iOS non-working.

Thanks.

**Comment by richardjrossiii** [comment]
I'm not sure exactly what you're referring to, unfortunately. Are you referring to continuing on that task, and that callback not happening on the UI thread? If so, you should do a continuation with a specific `TaskScheduler` that calls back onto the UI thread.

AFAIR, Our documentation makes no guarantees in terms of which thread asynchronous callbacks are invoked on, and it's up to you to make sure you update your UI on the correct thread.

**Comment by johnthiriet** [comment]
Hi, thanks for the answer.
Reproducing the issue is simple and just consists in taking the Xamarin.iOS sample :
https://www.parse.com/downloads/windows/ParseXamarinPushSample-CSharp/latest

Beside inserting the necessary API keys to use Parse, I made no modification whatsoever to the project.

Using the latest version of the Parse SDK, the call to ParseClient.Initialize doesn't complete successfully as it doesn't call the Parse API to register the Installation as it does on Android.

When using the full Parse SDK source code instead of the pre-compiled DLL and debugging using Visual Studio 2013 catching all thrown exceptions we can see that a UIKitThreadAccessException is thrown preventing the network call to Parse to occur.

Please refer to the screenshot for the error.

<img width="1440" alt="screen shot 2015-10-12 at 22 07 57" src="https://cloud.githubusercontent.com/assets/10599907/10437516/f0693e32-712d-11e5-98a6-709df674f523.png">

The exception is thrown by a call the getter of the Badge property of the ParseInstallation.iOS class file.
It looks like setting the UIApplication.SharedApplication.ApplicationIconBadgeNumber is not supported from another thread than the UI Thread. And one easy way to fix the issue is to refactor the calling code as in my first post.

Because of this exception, any new installation of the Parse SDK is not uploaded to Parse servers making push impossible.

I hope this will help you better understand the issue.

Please feel free to ask any questions if anything remains unclear.

 


The exception occurs inside Parse SDK code and is not rethrown to the client application therefore, there is no easy way to see that the error happened beside using Parse's source code instead of pre-compiled packages or NuGet packages.

**Comment by richardjrossiii** [comment]
Ah, that makes a lot more sense now. I'll create a PR shortly to fix our usage of it here. Thanks for your help!
