### ISSUE TITLE
Returning object from cloud missing Dates "createdAt" and "updatedAt"

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-dotNET#38]
Just started getting some errors today. When parsing the Date in "ParseDecoder.ParseDate", input is null. Which results in an exception at "DateTime.ParseExact" "s or format is null."

After adding some logging to the methods calling "ParseDecoder.ParseDate", specifically - "ParseObjectCoder.Decode":

	DateTime? createdAt = extractFromDictionary<DateTime?>(mutableData, "createdAt", (obj) => {
		return ParseDecoder.ParseDate(obj as string);
	});
	DateTime? updatedAt = extractFromDictionary<DateTime?>(mutableData, "updatedAt", (obj) => {
		return ParseDecoder.ParseDate(obj as string);
	});

The dictionary that contains "createdAt" and "updatedAt" doesn't actually contain those keys, resulting in "null" being sent to ParseDecoder.ParseDate. In other words, When logging all keys and values inside "mutableData", "updatedAt" and "createdAt" don't exist.

The strange this is, adding a custom Date column to my class works, the data is returned as decoded correctly.

Is there a reason why "createdAt" and "updatedAt" aren't being returned in the cloud code response? Or maybe that data is getting lost somehow?

For now I've added this to the ParseDeoder.ParseDate method:

	internal static DateTime? ParseDate(string input) {

		if (string.IsNullOrEmpty(input)) {

			UnityEngine.Debug.LogWarning("ParseDate is empty! returning null");
			return null;
		}

		// TODO(hallucinogen): Figure out if we should be more flexible with the date formats
		// we accept.
		return DateTime.ParseExact(input, ParseClient.DateFormatString, CultureInfo.InvariantCulture);
	}

**Comment by richardjrossiii** [comment]
This was a regression in the JS SDK release 1.6.0, and was fixed in 1.6.1 AFAIK. If you update the version of parse in your cloud code, it should start working again.

I'm closing this issue, but feel free to reopen it if the problem persists.

**Comment by cfoulston** [comment]
Ok Thanks, but how do you update the version of parse in cloud code?

when I type: "parse jssdk -a" it says I'm on the latest

if I change to "parse jssdk 1.6.1" it changes, but the problem still exists.
