### ISSUE TITLE
Parse.dll 1.6.0 does not have a strong name and unable to sign it myself

### ISSUE THREAD

**Issue by Matthius** [ParsePlatform/Parse-SDK-dotNET#46]
It appears Parse.dll and Parse.NetFx45.dll from the .net 4.5 package do not have a strong name.

I have followed this guide to sign it personally: http://ryanfarley.com/blog/archive/2010/04/23/sign-a-.net-assembly-with-a-strong-name-without-recompiling.aspx 

But I still have this exception when launching my app:

>Could not load file or assembly 'Parse, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
 StackTrace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Parse.ParseClient.GetParseType(String name)
   at Parse.ParseClient..cctor()

When showing properties of the said dlls in visual studio, it does say they have a strong name.

Any idea?

EDIT: same thing for 1.6.1

EDIT2: I sign my application with a .pfx. Does it change anything? I have other Dlls that do not have a strong name (WpfAnimatedGif) and there is no problem with them.

**Comment by hallucinogen** [comment]
This is a valid issue. I'll fix the internal deploy script to re-sign the lib. There'll be no PR since it's an internal script. You can expect this to be fixed in `1.6.2`

**Comment by Matthius** [comment]
Ok nice! Thanks for that! :)

**Comment by mbilling** [comment]
Release 1.6.2 is not signed - could you please fix :)
I have tested download from parse.com and nuget,- same result

C:\Users\mb\Downloads\Parse-1.6.2>sn -v Parse.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

Parse.dll does not represent a strongly named assembly

C:\Users\mb\Downloads\Parse-1.6.2>

**Comment by richardjrossiii** [comment]
AFAIK, 1.7.0 is now fully signed and ready to go, so I'm closing this issue out. Let me know if you run into any problems!
