### ISSUE TITLE
Consistently Fill ParseInstallation Fields

### ISSUE THREAD

**Issue by hallucinogen** [ParsePlatform/Parse-SDK-dotNET#51]
Saving the ParseInstallation object leaves the following fields unpopulated:
- `appIdentifier`
- `appName`
- `timeZone`
- `badge` (this is probably fine left unpopulated)
- `parseVersion`
- `timeZone`

We need to fix it.

**Comment by danielseto** [comment]
Any updates about this issue? Is there an estimated date to fix it or at least a workaround?

**Comment by richardjrossiii** [comment]
This *should* have been fixed in #41, which is in the latest release, 1.6.2. Marking as closed, feel free to open another issue if this problem persists.
