### ISSUE TITLE
[Unity] ParseFile url not https

### ISSUE THREAD

**Issue by andymads** [ParsePlatform/Parse-SDK-dotNET#54]
I use WWW to download a ParseFile but now Unity on iOS is warning me that the given url needs to be https and that they will be removing the mechanism that allows http to work at the moment.

Will this be addressed by Parse?

**Comment by richardjrossiii** [comment]
We've already discussed this issue (or a similar one) on the iOS repo. (See [here](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/12)).

Our solution there is to rewrite HTTP ParseFile URLs into HTTPs.

The other solution would be to make end developers rewrite the URL themselves, as there may be use cases where we don't want to force HTTPs.

@hallucinogen What are your thoughts on using the first approach here?

**Comment by hallucinogen** [comment]
Sounds good. Let's rewrite ParseFile HTTP to HTTPS.

Attaching the diff made in iOS repo: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/pull/197/files

**Comment by andymads** [comment]
When will the SDK be updated for this?

**Comment by andymads** [comment]
SDK still at 1.6.1 on downloads page.
