### ISSUE TITLE
Notification doesn't show if no Android icon in Manifest

### ISSUE THREAD

**Issue by benjorsini** [ParsePlatform/Parse-SDK-dotNET#55]
Hi,

We have a Xamarin Forms iOS & Android app that uses the .NET SDK.
We spent a day try to figure out why the device didn't show any notification on Android when receiving a push.

The fact is : if you don't have `android:icon="@drawable/Icon"` in your manifest, no notification is shown. 

Using `ParsePush.ParsePushNotificationReceived +=  ParsePush.DefaultParsePushNotificationReceivedHandler;`, the push is received, the device vibrates, but no warning or error in the console saying that an icon is needed to show the notification.

It would be nice to either show a default notification or clearly specify it in the QuickStart guide.

Have a good day !

**Comment by gusennan** [comment]
Hi @benjorsini, this is a common issue that people have with Android notifications, and I agree would be helpful if it were added to their documentation.  To their benefit, though, it is documented in the Android documentation [here](http://developer.android.com/training/notify-user/build-notification.html).  Maybe Parse could ship with a default icon in its default notification handler so at least it would work on first go, whether or not it's the right icon or not.

**Comment by richardjrossiii** [comment]
@gusennan. is correct, this is Android's default behavior, and seeing as how how I'm not aware of any good way to ship an arbitrary icon with our library downloads, I'm going to close this.

There's really nothing to fix. If this really ends up being a long term issue, *maybe* we can add a log message stating that there was no icon set in the application manifest, but seeing as this should *never* be seen in production, I don't think even that action is necessary.

**Comment by gusennan** [comment]
What would be helpful, I think, is just noting this in the documentation where there's mention of adding a custom push-notification handler on Android.  The _RebuyParsePushNotificationReceivedHandler_ sets the icon of the push notification, (which is like a default icon) and so works "out of the box".  When other's add their own NotificationReceivedHandler, it's a common issue to not realize that it's necessary to set the icon ID of the push.
