### ISSUE TITLE
Support for tvOS?

### ISSUE THREAD

**Issue by bbartlett** [ParsePlatform/Parse-SDK-dotNET#56]
Any plans for supporting tvOS? From this Parse iOS SDK thread ( https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/250 ), it looks like they are making progress in the native-code side -- can you leverage any of their work?  (Unfortunately, there are definitely still some hurdles to work around such as not having any persistent local storage at all...)

**Comment by richardjrossiii** [comment]
Duplicate of #24
