### ISSUE TITLE
[Unity] Android manifest error log when manifest is correct

### ISSUE THREAD

**Issue by mpaolino** [ParsePlatform/Parse-SDK-dotNET#62]
Seems devices cannot register for push notifications in Android due to a problem with how AndroidManifest is handled (?). 

Using:
- Parse 1.6.1
- Android SDK 23.0.1
- Google Play Service rev 27 
- Unity 5.1.3f1 Personal

Error in adb logcat: https://gist.github.com/mpaolino/e363a2c18ec208ed6163
AndroidManifest of the app (configured as per documentation): https://gist.github.com/mpaolino/867fba4c081f50d1cdb0

Test device: Google Nexus 5

**Comment by richardjrossiii** [comment]
It would appear that you're missing the `VIBRATE` permission in your manifest. Try adding that and let me know what happens.

**Comment by mpaolino** [comment]
Same thing

New manifest: https://gist.github.com/mpaolino/51225bcd9b216be70101
New log: https://gist.github.com/mpaolino/dd487355a606a6065455

**Comment by mpaolino** [comment]
BTW, I managed to have the Unity minimal tutorial running by fixing the AndroidManifest https://github.com/ParsePlatform/PushTutorial and it produces the exact same result. Not exactly sure what version of Parser this is, apparently 1.5.3 by last relevant commit.

**Comment by LucasLMartini** [comment]
I need to add to this error. I've followed the quickstart guide for Unity Android and quadruple-checked everything, it is just not working. The device never registers, I don't see any Android devices on my control panel.

Here is my manifest as well, this has been extracted straight from the APK utilizing apktool to decompress it, just to make sure Unity isn't fumbling multiple manifests:

https://gist.github.com/LucasLMartini/8e4eb99be2c8338662a2

**Comment by hallucinogen** [comment]
As long as it has ParsePush.jar under `Assets/Plugins/Android`, the GCM will always try to register and inform us why it's not working by looking at the LogCat. Typically the error will be around "Doesn't have enough permission" all "Doesn't register correct service." Can you take a look at the LogCat and paste it?

Further reading:
1. https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParsePush/src/main/java/com/parse/ParsePushService.java#L160
2. https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParsePush/src/main/java/com/parse/ManifestInfo.java#L189
3. https://github.com/ParsePlatform/Parse-SDK-dotNET/blob/master/ParsePush/src/main/java/com/parse/ManifestInfo.java#L201

**Comment by LucasLMartini** [comment]
Ok, now this is even weirder, I only just realized logcat -s Unity wouldn't get this stuff, so here's what I tried and its output:

https://gist.github.com/LucasLMartini/767981a57a5000c42e44

It does say GCM registration successful, but I don't see any Android devices to push to back in Parse's web control panel!

The odd part is this it seems:
"Cannot save Installation because GCM registration is handled while the app isbackgrounded"

My app runs a video on the first scene's Awake() methods, so I guess Unity.ApplicationPaused() is true. Is that an issue though? Does the message need to get back to Unity for it all to work?

**Comment by mpaolino** [comment]
Just for the record, this didn't work for me so I just gave up on it and use another solution.

**Comment by LucasLMartini** [comment]
I'll answer my own question:

Unity cannot be paused/backgrounded between ParseInitializeBehaviour running Awake() and receiving the GCM response.

If it is paused, Parse's gameObject won't receive the message to save the user data.

I just changed my scene setup and code to make the ParseInitializeBehaviour object be instantiated only after the video has finished playing and it worked.
