### ISSUE TITLE
Suggestion: Make ParseClient.ConvertTo public

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-dotNET#67]
Would be super helpful if this method were public, then we could get typed values out of generic objects returned from a parse cloud. i.e:

	//cloud code

	response.success({ object1:parseObject, object2:anotherParseObject })

	//Unity client

	IDictionary<string, object> result = response;

	ParseObject object1 = ParseClient.ConvertTo<ParseObject>(result["object1"]);

**Comment by richardjrossiii** [comment]
I agree! I think this would be useful to be made public. I'll send a PR in a little bit to see how others on the team feel.
