### ISSUE TITLE
Unity Android can't find cloud code functions

### ISSUE THREAD

**Issue by cfoulston** [ParsePlatform/Parse-SDK-dotNET#68]
Using Unity SDK 1.6.1

Calling any cloud code function from Android results in:

 "OtherCause: java.io.FileNotFoundException: https://api.parse.com/1/functions/methodName"

iOS works, Unity editor works

**Comment by richardjrossiii** [comment]
Thanks for the report! Any chance we can get a full stack trace from this exception?

**Comment by cfoulston** [comment]
Sure, here's the stack trace from ADB

	E/Unity   ( 2332): Parse Exception: (OtherCause) java.io.FileNotFoundException: https://api.parse.com/1/functions/testMethod
	E/Unity   ( 2332):   at Parse.Internal.ParseCommandRunner+<>c__DisplayClass2.<RunCommandAsync>b__1 (System.Threading.Tasks.Task`1 t) [0x00000] in <filename unknown>:0
	E/Unity   ( 2332):   at Parse.Internal.InternalExtensions+<>c__DisplayClass1`2[System.Tuple`2[System.Net.HttpStatusCode, System.String],System.Tuple`2[System.Net.HttpStatusCode,System.Collections.Generic.IDictionary`2[System.String,System.Object]]].<OnSuccess>b__0 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0
	E/Unity   ( 2332):   at Parse.Internal.InternalExtensions+<>c__DisplayClass7`1[System.Tuple`2[System.Net.HttpStatusCode, System.Collections.Generic.IDictionary`2[System.String,System.Object]]].<OnSuccess>b__6 (System.Threading.Tasks.Task t) [0x00000] in <filename unknown>:0
	E/Unity   ( 2332):   at System.Threading.Tasks.Task+<>c__DisplayClass3`1+<>c__DisplayClass5[System.Threading.Tasks.Task`1[System.Tuple`2[System.Net.HttpStatusCode,System.Collections.Generic.IDictionary`2[System.String,Sy

**Comment by cfoulston** [comment]
Ok I found the issue, I didn't have the required .jar files as described here:

https://parse.com/apps/quickstart#parse_push/unity/android/existing

also, looks like the Plugins/Android folder must exist under Assets/Parse.Unity/Plugins/Android
