### ISSUE TITLE
Invalid ParseRelation returned if the object has no data for the relation.

### ISSUE THREAD

**Issue by kostub** [ParsePlatform/Parse-SDK-dotNET#72]
I have code in my user class to get contacts as follows:
```C#
        [ParseFieldName("contacts")]
        public ParseRelation<User> Contacts
        {
            get { return GetRelationProperty<User>(); }
        }
```
If the `contacts` field on the user is null then if I use the following code I get an `ArgumentNullException` when accessing the Query field of the returned relation.

```C#
var contacts = user.Contacts;
var query = contacts.Query;
```
My guess is this happens due to line 1339 in ParseObject.cs:
```C#
    public ParseRelation<T> GetRelation<T>(string key) where T : ParseObject {
      // All the sanity checking is done when add or remove is called.
      ParseRelation<T> relation = null;
      TryGetValue(key, out relation);
      return relation ?? new ParseRelation<T>(this, key);
    }
```
In the case where there is no data, the returned relation is `null` and thus it uses the constructor to create a new `ParseRelation`. However this constructor does not set the `targetClassName` on the `ParseRelation`. This results in the call to `Query` to throw an `ArgumentNullException` on `className`.

Instead line 1139 should be changed to use the other constructor which takes the `targetClassName`  as a parameter. It should get the `className` from `T` using the `ParseClassName` attribute on `T`.

**Comment by richardjrossiii** [comment]
Thanks for the report. I'll look into the `ParseRelation` constructor and see what's up.
