### ISSUE TITLE
Yellow warning icon on parse package in Xamarin Studio Mac

### ISSUE THREAD

**Issue by yozzozo** [ParsePlatform/Parse-SDK-dotNET#89]
On Xamarin Studio 5.10.871 (latest as of this writing), adding the parse NuGet package into my iOS project (Parse 1.6.2, also latest as of this writing) -- after install and restart of Xamarin Studio, the package is marked with a yellow exclamation warning icon.  When you hover over this icon, it says "Package is not restored".

This issue persists between updating the package (I had it ever since I first installed Parse .NET SDK 1.6.1).  

I noticed that if I followed the instructions in the last comment here:
https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/34
and restarted Xamarin Studio, the issue was resolved.  I just wanted to mention this to hopefully get the fix permanently applied to the NuGet package so I won't have to keep applying it and other users won't have to experience the issue.

Thanks!

**Comment by richardjrossiii** [comment]
As mention on #34, this is a bug with Xamarin Studio that has been fixed on the beta channel (no idea why they haven't updated yet).

Seeing as we can't personally fix this bug, I'm going to close this for now.
