### ISSUE TITLE
NullReferenceException triggered when setting ParseACL to new ParseObject.

### ISSUE THREAD

**Issue by Malmo92** [ParsePlatform/Parse-SDK-dotNET#90]
Getting a NullReferenceException when I am trying to set the ParseACL to an instantiated ParseObject.

The following line causes the issue for me in the Parse .NET SDK 1.6.2:

var po = new ParseObject("Table");
po.ACL = new ParseACL(ParseUser.CurrentUser);

This code is run after user is authenticated. ParseUser.CurrentUser is not null.

**Comment by richardjrossiii** [comment]
Confirmed bug. PR coming shortly.

**Comment by richardjrossiii** [comment]
As a temporary work around until the next SDK version is released, you can create a concrete subclass of `ParseObject`, and register that, and then the `ACL`, `ObjectId`, `CreatedAt`, and `UpdatedAt` properties will work properly once again.

**Comment by ViolentCrumble** [comment]
Can you give an example of the fix...
