### ISSUE TITLE
Obvious bug in DefaultParsePushNotificationReceivedHandler for Android

### ISSUE THREAD

**Issue by Jeern** [ParsePlatform/Parse-SDK-dotNET#93]
I have a problem with this setup from the Parse documentation.
ParsePush.ParsePushNotificationReceived += ParsePush.DefaultParsePushNotificationReceivedHandler;

It does not work. The push is recieved by the device which I can confirm because I can attach another eventhander that just prints af Console.Writeline - so far so good. Opening up the code for DefaultParsePushNotificationRecievedHandler reveals an obvious bug.

```
if (pushData == null || (!pushData.ContainsKey("alert") && !pushData.ContainsKey("title"))) {
  return;
}

string title = pushData.ContainsKey("title") ? pushData["title"] as string : ManifestInfo.DisplayName;
string alert = pushData.ContainsKey("alert") ? pushData["alert"] as string : "Notification received.";
```

You do not allow alerts without a title. Even though you have clearly stated that this is allowed in your documentation. And furthermore you do not send a title in your own Test push. Which means the test push will never work. This is clearly why you set the title to DisplayName - this will never happen of course because of the first if.

Despite this obvious bug, it did not help me to set a title, so I will have to look elsewhere for my problem.

**Comment by richardjrossiii** [comment]
I'm not sure I follow. The `if` statement you're referring to checks if **both** `alert` and `title` are empty, and if so, do nothing.

Then, we set the alert and title to be either the results of the JSON object, otherwise the default value (e.g. `ManifestInfo.DisplayName` for title, and "Notification Received" for alert).

**Comment by Jeern** [comment]
Yeah. Exactly - my bad. Apparently I cannot read a simple boolean expression. Must have seen AND as OR or something.

My problem turned out to be that I did not have a metadata tag in the AndroidManifest with a Push icon. 

Apparently this means that even though I receive the Push on the device it is not shown. Weird that this is not documented and that you get no errors indicating this is a problem.

I will close this issue. Sorry about the disturbance...
