### ISSUE TITLE
[Unity] -canOpenURL: failed for URL: "cydia://package/com.example.package"

### ISSUE THREAD

**Issue by Benzino** [ParsePlatform/Parse-SDK-dotNET#95]
When I attempt to run Unity app with Parse on an iPad mini ios 9.1, I get the following error:

-canOpenURL: failed for URL: "cydia://package/com.example.package" - error: "This app is not allowed to query for scheme cydia".

I understand this issue was raised before and marked as fixed, however it is still occurring for us. We are using v1.6.2 of the Parse Unity SDK on Unity v5.2.2.

**Comment by richardjrossiii** [comment]
There should be no way that this is coming from our .NET SDK. Nowhere in our code-base do we reference the `cydia` URL scheme, and the only time that we have done that IIRC is in old versions of our iOS/OSX native SDK.

I'd strongly recommend looking at other libraries as the culprit for this, it's certainly not us.

**Comment by cbothra** [comment]
Hi Benzino,
I am also facing the same issue. Did you managed to resolve it? Could you please share your resolution for this issue?
