### ISSUE TITLE
Getting WebException instead of ParseException for InvalidSessionToken

### ISSUE THREAD

**Issue by rehos** [ParsePlatform/Parse-SDK-dotNET#99]
Parse .NET SDK 1.6.2 within Xamarin iOS and Xamarin Android apps.

If the session of a user has been revoked (either by removing the session manually from the Session table or if user changed password on other device), the SDK now generates a WebException with status ProtocolError instead of a ParseException with code InvalidSessionToken.

Note: I can see the correct JSON with the correct parse error code is being returned from the Parse backend with HTTP status code 400.

**Comment by richardjrossiii** [comment]
That may have happened when we refactored HttpClient. I'll look into it. Thanks for the report!

**Comment by rehos** [comment]
I also noticed that a script error results in a WebException with status ProtocolError instead of a ParseException with code ScriptFailed.

**Comment by brett-estabrook** [comment]
I'm seeing a similar problem, whats the latest version I should downgrade to and see this fixed (or when is a fix coming out).

http://stackoverflow.com/questions/34340677/parseexceptions-not-getting-thrown-for-callfunctionasync

**Comment by hallucinogen** [comment]
This should be fixed in #132. Feel free to reopen if the problem persists
